import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";

import { LayoutApp } from "@layouts";

import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="header relative pt-16 items-center flex h-screen max-h-860-px">
                <div className="container mx-auto items-center flex flex-wrap">
                    <div className="w-full md:w-8/12 lg:w-6/12 xl:w-6/12 px-4">
                        <div className="pt-32 sm:pt-0">
                            <h2 className="font-semibold text-4xl text-emerald-800">
                                Giới thiệu chung
                            </h2>
                            <h1 className="font-semibold text-6xl text-teal-500">
                                Du lịch Việt Nam
                            </h1>
                            <p className="mt-4 text-lg leading-relaxed text-blueGray-500">
                                Đất nước ta trải qua hàng nghìn năm dựng nước, giữ nước.
                            </p>
                            <p className="mt-4 text-lg leading-relaxed text-blueGray-500">
                                Con người chân thành, mộc mạc chất phát. Những tháng ngày thống khổ
                                của cha ông đã viết lên những trang sử hào hùng. Vẻ đẹp từ tâm hồn,
                                từ con người ấy càng đẹp hơn khi chúng ta được tạo hóa ban tặng
                                thiên nhiên hùng vĩ, đường bờ biển chạy dài dọc theo hình chữ S của
                                tổ quốc. Còn điều gì tuyệt vời hơn khí có sông, có núi, có biển. Sự
                                hài hòa của thiên, nét đẹp hùng vĩ bao trùm lên những con người với
                                nét đẹp mộc mạc đậm chất Á Đông. Sẽ thật thiếu sót khi bạn không
                                dành cho cuộc đời những chuyến đi khám phá nét đẹp ấy của đất nước
                                tuyệt đẹp, của chính mình.
                            </p>
                            <div className="mt-12">
                                <a
                                    href="https://www.creative-tim.com/learning-lab/tailwind/nextjs/overview/notus?ref=nnjs-index"
                                    target="_blank"
                                    rel="noreferrer"
                                    className="get-started text-white font-bold px-6 py-4 rounded outline-none focus:outline-none mr-1 mb-1 bg-blueGray-400 active:bg-blueGray-500 uppercase text-sm shadow hover:shadow-lg ease-linear transition-all duration-150"
                                >
                                    Cẩm Nang Du Lịch
                                </a>
                                <a
                                    href="https://github.com/creativetimofficial/notus-nextjs?ref=nnjs-index"
                                    className="github-star ml-1 text-white font-bold px-6 py-4 rounded outline-none focus:outline-none mr-1 mb-1 bg-blueGray-700 active:bg-blueGray-600 uppercase text-sm shadow hover:shadow-lg"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    Nơi bạn muốn đến
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <img
                    className="absolute top-0 b-auto right-0 pt-16 sm:w-6/12 -mt-48 sm:mt-0 w-10/12 max-h-860-px"
                    src="/img/gioithieu.JPG"
                    alt="..."
                />
            </section>
        </div>
    );
};

Home.layout = (page: ReactElement) => {
    return <LayoutApp>{page}</LayoutApp>;
};

export default Home;
